name: GitHub Release
on:
  push:
    tags:
    - "*"

env:
  plugin_name: vk-blocks

jobs:
  tag:
    name: New release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # get the node version from the .node-version file
    - name: Read .node-version
      run: echo "##[set-output name=NODEVERSION;]$(cat .node-version)"
      id: nodenv

    # setup node based on the version from the .node-version file, fetched in the previous step
    - name: Setup Node.js (.node-version)
      uses: actions/setup-node@v1
      with:
        node-version: "${{ steps.nodenv.outputs.NODEVERSION }}"

    - name: Build
      run: |
        npm install
        npm run build:free
# PHPUnit 
    - name: Dist
      run : | 
        npx gulp dist:free
        cd dist/ && zip -r ${{ env.plugin_name }}.zip ${{ env.plugin_name }}/
        echo "---------"
        test -e dist/${{ env.plugin_name }}.zip
    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ steps.deploy.outputs.zip-path }}
        asset_name: ${{ github.event.repository.name }}.zip
        asset_content_type: application/zip